
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - '14'
install:
  - npm i npminstall && npminstall
before_script:
  - cp test/fixtures/redis/*.conf /tmp
  - redis-server /tmp/sentinel-26379.conf --sentinel
  - redis-server /tmp/sentinel-26380.conf --sentinel
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - redis-server
